export const API_CONFIG = {
  basePath: '/api',
  endpoints: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    owners: '/auth/owners',
    dashboard: '/dashboard',
    generatedActivity: '/generated-activity',
    wellness: '/wellness',
    activities: '/activities',
    athleteProgression: '/athlete-progression',
    settings: '/settings',
    coachSnapshot: '/coach-snapshot',
    vdot: '/vdot',
    dataExtractStatus: '/data-extract/status',
    dataExtractCredentials: '/data-extract/credentials',
    dataExtractGarminAuthReset: '/data-extract/garmin-auth/reset',
    dataExtractSync: '/data-extract/sync',
    dataExtractComprehensive: '/data-extract/comprehensive',
    garminOauthStart: '/garmin/oauth/start',
    garminOauthDisconnect: '/garmin/oauth/disconnect',
    customActivities: '/custom-activities',
    customActivitiesIngest: '/custom-activities/ingest',
    customActivitiesWorkoutUpdate: '/custom-activities/workout',
    activityMerges: '/activity-merges',
    weekOutlook: '/week-outlook',
    plannedActivities: '/planned-activities',
    plannedManualDone: '/planned-activities/manual-done',
    plannedIngest: '/planned-activities/ingest',
    plannedWorkoutUpdate: '/planned-activities/workout',
  },
} as const;
